name: Update Documentation

on:
  repository_dispatch:
    types:
      - update-documentation

jobs:
  updateDocumentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Extract Markdown from GPT-3.5 Turbo response
        id: extract-markdown
        run: echo "::set-output name=markdown::${{fromJson(github.event.client_payload.data).choices[0].text}}"

      - name: Run Custom Script
        run: |
          pwsh ./scripts/update_documentation_script_git.ps1 -FilePath ./src/solutions/gpt-pro/changelog.md -MarkdownData "${{ steps.extract-markdown.outputs.markdown }}"

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: ./src/solutions/gpt-pro/changelog.md
          commit-msg: Update resources  
          github-token: ${{ secrets.GITHUB_TOKEN }}