name: Update Documentation

on:
  repository_dispatch:
    types:
      - update-documentation

jobs:
  updateDocumentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Run Custom Script
        run: |
          pwsh ./scripts/update_documentation_script_git.ps1 -FilePath ./src/solutions/gpt-pro/changelog.md -MarkdownData "${{github.event.client_payload.data}}"
      
      - name: Check if auto-changes branch exists
        run: |
          if git show-ref --quiet refs/heads/auto-changes; then
            git checkout auto-changes
          else
            git checkout -b auto-changes
          fi

      - name: Commit changes and push to auto-changes branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Update documentation"
          git push origin auto-changes

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Automatically generated pull request
          body: Changes have been made automatically.
          branch: auto-changes
          base: main